#! /bin/bash
[[ "$1" =~ ^-h$\|^--help$ ]] && echo "archivedel ARCHIVE FILES_TO_DEL..." && return 0;

if [[ `file --mime-type -b "$1"` == "application/zip" ]]; then
    zip -d "$1" "$@";
else
    rar d "$1" "$@"
fi;
