#!/usr/bin/env python

import sys, argparse
from math import (exp, pi)

def awg2mm(awg):
    return exp(2.1104-0.11594*awg)
def awg2inches(awg):
    return exp(-1.12436-0.11594*awg)

def awg2area(awg, imperial=False):
    if imperial:
        return pi * (0.5*awg2inches(awg))**2
    else:
        return pi * (0.5*awg2mm(awg))**2

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='awg2diameter AWG')
    parser.add_argument('awg', type=int, help='gauge (AWG)')
    parser.add_argument('-i', '--imperial', help='print diameter in inches squared', action="store_true")
    args = parser.parse_args()
    if args.imperial:
        print("%f square inches" % awg2area(args.awg, True))
    else:
        print("%f square mm" % awg2area(args.awg))
