#!/usr/bin/env python

import sys, argparse
from math import exp

def awg2mm(awg):
    return exp(2.1104-0.11594*awg)
def awg2inches(awg):
    return exp(-1.12436-0.11594*awg)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='awg2diameter AWG')
    parser.add_argument('awg', type=int, help='gauge (AWG)')
    parser.add_argument('-i', '--inches', help='print diameter in inches', action="store_true")
    args = parser.parse_args()
    if args.inches:
        print("%f inches" % awg2inches(args.awg))
    else:
        print("%f mm" % awg2mm(args.awg))
