#! /bin/bash

tmpdir=`mktemp -d`;
cd $tmpdir;
if [[ `file --mime-type -b "$1"` == "application/zip" ]]; then
    unzip "$1" >/dev/null;
else
    unrar e "$1" >/dev/null;
fi;
identify "$(find $tmpdir -type f)" | sed -r 's/.*\b[0-9]+x([0-9]+)\b.*/\1/';
