#! /bin/bash

if [[ "$1" =~ ^-h$ || ^--help$ ]]; then
    cat <<EOF
copy-filename FILE

Copies the name of FILE (without directory path) to clipboard.
By default, filename extensions are removed.

-x --keep-extensions  --  keep filename extensions
EOF
    exit 0;
fi;

if echo "$1" | egrep -q '^-x$|^--keep-extension$'; then
    extension="t";
    shift;
fi

if [[ -n $extension ]]; then
    name=`basename "$1"`;
else
    name=`basename "$1" | sed -r 's/\..+//'`;
fi;
echo "$name" | xclip -i;
