#! /usr/bin/env node

process.stdin.on('data', data => {
    const s = data.toString();
    const [r, g, b] = [s.slice(0, 2), s.slice(2, 4), s.slice(4, 6)].map (sn=>parseInt(sn, 16));
    console.log(`rgb(${r}, ${g}, ${b})`);
});
