#! /bin/sh
# Troy S Pracy 2014-2015. MIT licensed.

# Create HTML links to directories and files

if [ -e "$outfile" ]
then
    >&2 echo "The file '"$outfile"' already exists. Exiting."
    exit
fi

outfile="${2:-index.html}"
dir="${1:-.}"

dirlinks=$(mktemp)
filelinks=$(mktemp)
find "$dir" -mindepth 1 -maxdepth 1 -type d -printf "      <a class='directory' href=\"%p\">%f</a><br>\n" >> $dirlinks
find "$dir" -mindepth 1 -maxdepth 1 -type f -printf "      <a class='file' href=\"%p\">%f</a><br>\n" >> $filelinks

# Create index.html file

cat << EOF > "$outfile"
<html>
  <meta charset="UTF-8">

  <style media="screen" type="text/css">
    .directory {
      text-align: center;
    }
    .directory a {
      font-weight: bold;
      text-decoration: none;
    }
    .directory a:link {
      color: #2030B0; <!-- blue -->
    }
    .directory :link:hover {
      color: #FF77DF; <!-- pink -->
    }
    .directory a:visited {
      color: #7070DC; <!-- light moody blue -->
    } 
    .directory :visited:hover {
      color: #FF77DF; <!-- pink -->
    } </style>
  <style media="screen" type="text/css">
    .file {
      text-align: center;
    }
    .file a {
      font-weight: bold;
      text-decoration: none;
    }
    .file a:link {
      color: #000000; <!-- black -->
    }
    .file :link:hover {
      color: #4285F4; <!-- light blue -->
    }
    .file a:visited {
      color: #777777; <!-- grey -->
    }
    .file :visited:hover {
      color: #4285F4; <!-- light blue -->
    } </style>
  <style media="screen" type="text/css">
    .heading {
      text-align: center;
    } </style>
  <style media="screen" type="text/css">
    .boxed { 
      margin: auto;
      padding: 20px; 
      width: auto; 
      display: inline-block;
      text-align: left;
    } </style>
  <style media="screen" type="text/css">
    .withborder {
      border: solid;
    } </style>

  <body>
EOF

printf '    <p>\n' >> "$outfile"
printf '      <h1 class="heading">'  >> "$outfile"
printf "${PWD##*/}" >> "$outfile"
printf '</h1>\n' >> "$outfile"
printf '    </p>\n' >> "$outfile"
printf '    <p>\n' >> "$outfile"
printf '      <h2 class="heading">contents</h2><br>\n' >> "$outfile"
printf '      <div class="directory">\n' >> "$outfile"
printf '        <div class="boxed">\n' >> "$outfile"
printf "          <a href=.>DIRECTORY</a>\n" >> "$outfile"
printf '        </div>\n' >> "$outfile"
printf '      </div><br>\n' >> "$outfile"
printf '      <div class="directory">\n' >> "$outfile"
printf '        <div class="boxed">\n' >> "$outfile"
sort -fV $dirlinks >> "$outfile"
printf '        </div>\n' >> "$outfile"
printf '      </div><br>\n' >> "$outfile"
printf '      <div class="file">\n' >> "$outfile"
printf '        <div class="boxed withborder">\n' >> "$outfile"
sort -fV $filelinks >> "$outfile"

cat << EOF >> "$outfile"
        </div>
      </div><br>
    </p>
  </body>
</html>
EOF

