#! /bin/sh
# Troy S Pracy 2014. MIT licensed.

# Create HTML links to directories and files

dirlinks=$(mktemp)
filelinks=$(mktemp)
find . -mindepth 1 -maxdepth 1 -type d -printf "      <a class='directory' href=%p>%f/</a><br>\n" >> $dirlinks
find . -mindepth 1 -maxdepth 1 -type f -printf "      <a class='file' href=%p>%f</a><br>\n" >> $filelinks

# Create index.html file

printf '<html>\n' > index.html

printf '  <style media="screen" type="text/css">\n' >> index.html
printf '    .directory { font-weight: bold; color: red; }\n' >> index.html
printf '  </style>\n' >> index.html
printf '  <style media="screen" type="text/css">\n' >> index.html
printf '    .file { fontweight: normal; color: blue; }\n' >> index.html
printf '  </style>\n' >> index.html

printf '  <body>\n' >> index.html
printf '    <p>\n' >> index.html
printf '      <h1>'  >> index.html
printf "${PWD##*/}" >> index.html
printf '</h1>\n' >> index.html
printf '    </p>\n' >> index.html
printf '    <p>\n' >> index.html
printf '      <h2>contents</h2><br>\n' >> index.html
printf "      <a class='directory' href=.>./</a><br>\n" >> index.html
sort -fV $dirlinks >> index.html
sort -fV $filelinks >> index.html
printf '    </p>\n' >> index.html

printf '  </body>\n' >> index.html

printf '</html>\n' >> index.html
