#! /bin/bash

# Find the One Piece tankōbon volume containing a given chapter
# Data scraped from the One Piece Wiki at:
#     http://onepiece.wikia.com/wiki/Chapters_and_Volumes
# Uses onepiece-list-volume to do extract the volume data.

if [[ "$1" =~ ^-h$|^--help$ ]]; then
    cat <<EOF
onepiece-find-volume CH
    Find the volume containing chapter no. CH
EOF
    exit 0;
fi;

url='http://onepiece.wikia.com/wiki/Chapters_and_Volumes';
ch=`printf %03d "$1"`;
for vol in {1..100}; do
    if onepiece-list-volume $vol | grep -Pq "^$ch"; then
        echo $vol;
        exit
    fi;
done;
