#!/bin/bash

if [[ "$1" =~ ^-h$|^--help$ ]]; then
    cat <<EOF
Print contents of:
  $SH_ALIAS_FILE
  All files listed in $SH_FUNCTION_FILES
  All scripts in $SCRIPTS_DIRECTORY
EOF
    return 0; fi;
IFS=:
files="$SH_ALIAS_FILE:$SH_FUNCTION_FILES";
filesarr=(${files});
for f in "${filesarr[@]}"; do
    fn="${f/\~/$HOME}";
    echo "$fn $f"
    cat -n "$fn" | sed "s|^|$f:|"
    echo;
done;
find -L $SCRIPTS_DIRECTORY -type f ! -path '*/.git/*' | while read -r f; do
    echo "$f"
    ndigits_=$(wc -l < "$f" | wc -c);
    ndigits=$(( ${ndigits_:-0} ? $ndigits_ : 3 ));
    tempf=`tempfile`;
    nl -w $ndigits "$f" > $tempf;
    paste <(cat $tempf|sed "s/.*/${f##*/}   /") $tempf;
done;
echo "FIXME"
