#!/usr/bin/env bash

if [[ "$1" =~ ^--?h(elp)?$ ]]; then
    cat <<EOF
runmaff [-h] [-q] file [program]
    Run a MAFF file using default or chosen program for HTML files.

    Extracts the MAFF file into a temp directory and calls PROGRAM, if
    specified, or otherwise the program called by xdg-open.

    Options:
      -h --help    display this help
      -q --quiet   do not print messages
      --debug      show debugging info
EOF
    exit;
fi;

exec 3>&1;

while [[ "$1" =~ "^-" ]]; do
    case "$1" in
        (-q | --quiet)
            exec 3>/dev/null;
            shift ;;
        (--debug)
            debug=true;
            shift ;;
    esac;
done;


filepath=`realpath "$1"`
filename="${filepath##*/}"
basename="${filename%.*}"
safename=`echo "$basename" | tr " \t" "__"`

program="${2:-xdg-open}"

mkdir -p /tmp/runmaff/

dir=`mktemp -d "/tmp/runmaff/$safename.XXXX"`
echo "temp dir: $dir" >&3
{
	cd "$dir"
	unzip "$filepath" >&3

  if [[ -n $debug ]]; then
      echo "filepath: $filepath";
      echo "filename: $filename";
      echo "basename: $basename";
      echo "safename: $safename";
      echo "program: $program";
      echo "dir: $dir";
	    echo ./"$basename"/index.html

  else
	    "$program" ./"$basename"/index.html >&3
  fi;
}
