#!/usr/bin/env sh
args=${@:-'-mkpE -np -nH'}
default_addr="$(xsel -ob)"
read -p "address (default: $default_addr): " addr
printf "wget -c -N %s %s\n" "$args" ${addr:-"$default_addr"} > update
chmod a+x update
./update
